# Generated by Django 5.0.6 on 2026-08-11 08:51

import api.models
import api.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=160,
                        unique=True,
                        validators=[api.validators.validate_slug],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("duration", models.CharField(blank=True, default="", max_length=80)),
                ("short_description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("activity_packages", models.JSONField(blank=True, default=list)),
                ("overview", models.TextField(blank=True, default="")),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("good_to_know", models.JSONField(blank=True, default=list)),
                ("inclusions_included", models.JSONField(blank=True, default=list)),
                ("inclusions_not_included", models.JSONField(blank=True, default=list)),
                ("meeting_pickup", models.TextField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "pickup_time",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("what_to_bring", models.JSONField(blank=True, default=list)),
                ("terms", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-show_on_home", "title"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=40, unique=True)),
                ("customer_name", models.CharField(max_length=180)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[api.validators.validate_phone],
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("package", "Package"),
                            ("hotel", "Hotel"),
                            ("activity", "Activity"),
                            ("visa", "Visa"),
                            ("deal", "Deal"),
                        ],
                        default="package",
                        max_length=20,
                    ),
                ),
                ("item_slug", models.CharField(blank=True, default="", max_length=200)),
                (
                    "item_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("travel_date", models.DateField(blank=True, null=True)),
                ("pax", models.PositiveIntegerField(default=1)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[api.validators.validate_non_negative],
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("authorised", "Authorised"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("package", "Package"),
                            ("visa", "Visa"),
                            ("activity", "Activity"),
                            ("deal", "Deal"),
                            ("hotel", "Hotel"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("handled", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("google_form_sent", models.BooleanField(default=False)),
                ("delivery_log", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Contact message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=160,
                        unique=True,
                        validators=[api.validators.validate_slug],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("package", "Package"),
                            ("visa", "Visa"),
                            ("activity", "Activity"),
                            ("hotel", "Hotel"),
                        ],
                        default="package",
                        max_length=20,
                    ),
                ),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("short_description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, default="")),
                ("duration", models.CharField(blank=True, default="", max_length=80)),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("inclusions_included", models.JSONField(blank=True, default=list)),
                ("inclusions_not_included", models.JSONField(blank=True, default=list)),
                ("itinerary", models.JSONField(blank=True, default=list)),
                ("activity_packages", models.JSONField(blank=True, default=list)),
                ("good_to_know", models.JSONField(blank=True, default=list)),
                ("meeting_pickup", models.TextField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "pickup_time",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("what_to_bring", models.JSONField(blank=True, default=list)),
                ("rooms", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("policies", models.JSONField(blank=True, default=list)),
                ("visa_type", models.CharField(blank=True, default="", max_length=120)),
                ("validity", models.CharField(blank=True, default="", max_length=120)),
                ("documents_required", models.JSONField(blank=True, default=list)),
                ("eligibility", models.JSONField(blank=True, default=list)),
                ("terms", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-show_on_home", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[api.validators.validate_phone],
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("google_form", "Google Form"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("form", "Form"),
                        ],
                        default="form",
                        max_length=20,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("package", "Package"),
                            ("visa", "Visa"),
                            ("activity", "Activity"),
                            ("deal", "Deal"),
                            ("hotel", "Hotel"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_visa", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="home | assistance | package | deal visa | …",
                        max_length=40,
                    ),
                ),
                ("item_type", models.CharField(blank=True, default="", max_length=30)),
                (
                    "item_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("item_slug", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source_page",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("google_form_sent", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "whatsapp_url",
                    models.URLField(blank=True, default="", max_length=1200),
                ),
                ("delivery_log", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("place", models.CharField(blank=True, default="", max_length=160)),
                ("images", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("video_url", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomeGallerySlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("images", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Home gallery slider",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomeHeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(blank=True, default="", max_length=160)),
                ("short_description", models.TextField(blank=True, default="")),
                (
                    "button_text",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "button_link",
                    models.CharField(blank=True, default="/packages", max_length=200),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Home hero slide",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=160,
                        unique=True,
                        validators=[api.validators.validate_slug],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("short_description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("stars", models.PositiveSmallIntegerField(default=5)),
                ("overview", models.TextField(blank=True, default="")),
                ("rooms", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("policies", models.JSONField(blank=True, default=list)),
                ("terms", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-show_on_home", "name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=160,
                        unique=True,
                        validators=[api.validators.validate_slug],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("duration", models.CharField(blank=True, default="", max_length=80)),
                ("short_description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("overview", models.TextField(blank=True, default="")),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("inclusions_included", models.JSONField(blank=True, default=list)),
                ("inclusions_not_included", models.JSONField(blank=True, default=list)),
                ("itinerary", models.JSONField(blank=True, default=list)),
                ("terms", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-show_on_home", "title"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                (
                    "payment_link",
                    models.URLField(blank=True, default="", max_length=600),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("authorised", "Authorised"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=80, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                ("label", models.CharField(blank=True, default="", max_length=180)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("avatar", models.CharField(blank=True, default="", max_length=500)),
                (
                    "avatar_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored image URL (filled automatically on upload)",
                        max_length=500,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "show_on_home",
                    models.BooleanField(default=False, help_text="Show on home page"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=160,
                        unique=True,
                        validators=[api.validators.validate_slug],
                    ),
                ),
                ("destination", models.CharField(max_length=160)),
                ("visa_type", models.CharField(blank=True, default="", max_length=120)),
                (
                    "processing_days",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("validity", models.CharField(blank=True, default="", max_length=120)),
                ("short_description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "offer_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                ("flag", models.CharField(blank=True, default="", max_length=500)),
                (
                    "flag_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.media_upload_to
                    ),
                ),
                ("overview", models.TextField(blank=True, default="")),
                ("documents_required", models.JSONField(blank=True, default=list)),
                ("eligibility", models.JSONField(blank=True, default=list)),
                ("terms", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-show_on_home", "destination"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="adyen", max_length=20)),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("payment_link", models.URLField(blank=True, default="")),
                ("invoice_url", models.URLField(blank=True, default="")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("authorised", "Authorised"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="api.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
